{
 "cells": [
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Data Preprocessing"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "# importing necessary packages\n",
    "import pandas as pd\n",
    "from sklearn import preprocessing\n",
    "from sklearn.model_selection import KFold\n",
    "from sklearn import linear_model\n",
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "def coef_graph():\n",
    "    # plotting columns and their coef impact on predictions\n",
    "    coefs = pd.DataFrame(\n",
    "    regr.coef_,\n",
    "    #  columns=['Coefficients'], index=X_train.columns\n",
    "    columns=['Coefficients'], index=X.columns\n",
    "    )\n",
    "\n",
    "    # sort coefficients highest to lowest\n",
    "    coefs.sort_values(by=['Coefficients'], inplace=True)\n",
    "\n",
    "    # function to add value labels\n",
    "    def addlabels(x,y):\n",
    "        for i in range(len(x)):\n",
    "            plt.text(i,y[i],y[i])\n",
    "\n",
    "    # creating the graph\n",
    "    coefs.plot(kind='barh', figsize=(9, 7))\n",
    "    plt.title('Linear Regression Model')\n",
    "    plt.axvline(x=0, color='.5')\n",
    "    plt.subplots_adjust(left=.3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "# loading in data cleaned in data-preparation.ipynb\n",
    "svi_mortality_2014 = pd.read_csv('./data/svi-mortality-county/2014-svi-mortality.csv', index_col=0)\n",
    "svi_mortality_2020 = pd.read_csv('./data/svi-mortality-county/2020-svi-mortality.csv', index_col=0)\n",
    "\n",
    "# rename columns to match\n",
    "svi_mortality_2020.rename(columns={'E_POV150': 'E_POV'}, inplace=True)\n",
    "\n",
    "# drop columns with no equivalent\n",
    "svi_mortality_2014.drop('E_PCI', axis=1, inplace=True)\n",
    "svi_mortality_2020.drop(['E_HBURD', 'E_NOINT', 'E_AFAM', 'E_HISP', 'E_ASIAN', 'E_AIAN', 'E_NHPI', 'E_TWOMORE', 'E_OTHERRACE'], axis=1, inplace=True)\n",
    "\n",
    "# create new df with calculated change in estimated values\n",
    "diff_2020_2014 = svi_mortality_2020 - svi_mortality_2014\n",
    "\n",
    "# drop all na rows\n",
    "diff_2020_2014.dropna(inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>E_TOTPOP</th>\n",
       "      <th>E_HU</th>\n",
       "      <th>E_HH</th>\n",
       "      <th>E_POV</th>\n",
       "      <th>E_UNEMP</th>\n",
       "      <th>E_NOHSDP</th>\n",
       "      <th>E_AGE65</th>\n",
       "      <th>E_AGE17</th>\n",
       "      <th>E_DISABL</th>\n",
       "      <th>E_SNGPNT</th>\n",
       "      <th>E_MINRTY</th>\n",
       "      <th>E_LIMENG</th>\n",
       "      <th>E_MUNIT</th>\n",
       "      <th>E_MOBILE</th>\n",
       "      <th>E_CROWD</th>\n",
       "      <th>E_NOVEH</th>\n",
       "      <th>E_GROUPQ</th>\n",
       "      <th>E_UNINSUR</th>\n",
       "      <th>E_DAYPOP</th>\n",
       "      <th>Deaths</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1001</th>\n",
       "      <td>55136.0</td>\n",
       "      <td>22431.0</td>\n",
       "      <td>20304.0</td>\n",
       "      <td>7006.0</td>\n",
       "      <td>2252.0</td>\n",
       "      <td>5012.0</td>\n",
       "      <td>7321.0</td>\n",
       "      <td>14214.0</td>\n",
       "      <td>8700.0</td>\n",
       "      <td>1649.0</td>\n",
       "      <td>13103.0</td>\n",
       "      <td>249.0</td>\n",
       "      <td>842.0</td>\n",
       "      <td>4401.0</td>\n",
       "      <td>530.0</td>\n",
       "      <td>1081.0</td>\n",
       "      <td>442.0</td>\n",
       "      <td>5814.0</td>\n",
       "      <td>43534.0</td>\n",
       "      <td>114.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1003</th>\n",
       "      <td>191205.0</td>\n",
       "      <td>105563.0</td>\n",
       "      <td>73058.0</td>\n",
       "      <td>25988.0</td>\n",
       "      <td>7856.0</td>\n",
       "      <td>14615.0</td>\n",
       "      <td>33782.0</td>\n",
       "      <td>43186.0</td>\n",
       "      <td>26603.0</td>\n",
       "      <td>5027.0</td>\n",
       "      <td>32158.0</td>\n",
       "      <td>2571.0</td>\n",
       "      <td>18988.0</td>\n",
       "      <td>12200.0</td>\n",
       "      <td>998.0</td>\n",
       "      <td>2242.0</td>\n",
       "      <td>2611.0</td>\n",
       "      <td>27758.0</td>\n",
       "      <td>177010.0</td>\n",
       "      <td>465.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1005</th>\n",
       "      <td>27119.0</td>\n",
       "      <td>11833.0</td>\n",
       "      <td>9145.0</td>\n",
       "      <td>5832.0</td>\n",
       "      <td>1527.0</td>\n",
       "      <td>4790.0</td>\n",
       "      <td>4180.0</td>\n",
       "      <td>5862.0</td>\n",
       "      <td>4856.0</td>\n",
       "      <td>1098.0</td>\n",
       "      <td>14614.0</td>\n",
       "      <td>549.0</td>\n",
       "      <td>129.0</td>\n",
       "      <td>3175.0</td>\n",
       "      <td>178.0</td>\n",
       "      <td>802.0</td>\n",
       "      <td>2869.0</td>\n",
       "      <td>3760.0</td>\n",
       "      <td>29769.0</td>\n",
       "      <td>90.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1007</th>\n",
       "      <td>22653.0</td>\n",
       "      <td>8985.0</td>\n",
       "      <td>7078.0</td>\n",
       "      <td>3596.0</td>\n",
       "      <td>975.0</td>\n",
       "      <td>3466.0</td>\n",
       "      <td>3209.0</td>\n",
       "      <td>4903.0</td>\n",
       "      <td>3343.0</td>\n",
       "      <td>637.0</td>\n",
       "      <td>5717.0</td>\n",
       "      <td>112.0</td>\n",
       "      <td>163.0</td>\n",
       "      <td>2379.0</td>\n",
       "      <td>17.0</td>\n",
       "      <td>299.0</td>\n",
       "      <td>1576.0</td>\n",
       "      <td>2725.0</td>\n",
       "      <td>19274.0</td>\n",
       "      <td>57.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1009</th>\n",
       "      <td>57645.0</td>\n",
       "      <td>23868.0</td>\n",
       "      <td>20934.0</td>\n",
       "      <td>9866.0</td>\n",
       "      <td>2291.0</td>\n",
       "      <td>8567.0</td>\n",
       "      <td>9172.0</td>\n",
       "      <td>13877.0</td>\n",
       "      <td>9729.0</td>\n",
       "      <td>1650.0</td>\n",
       "      <td>6825.0</td>\n",
       "      <td>954.0</td>\n",
       "      <td>215.0</td>\n",
       "      <td>5497.0</td>\n",
       "      <td>344.0</td>\n",
       "      <td>823.0</td>\n",
       "      <td>572.0</td>\n",
       "      <td>6922.0</td>\n",
       "      <td>41857.0</td>\n",
       "      <td>143.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "      E_TOTPOP      E_HU     E_HH    E_POV  E_UNEMP  E_NOHSDP  E_AGE65  \\\n",
       "1001   55136.0   22431.0  20304.0   7006.0   2252.0    5012.0   7321.0   \n",
       "1003  191205.0  105563.0  73058.0  25988.0   7856.0   14615.0  33782.0   \n",
       "1005   27119.0   11833.0   9145.0   5832.0   1527.0    4790.0   4180.0   \n",
       "1007   22653.0    8985.0   7078.0   3596.0    975.0    3466.0   3209.0   \n",
       "1009   57645.0   23868.0  20934.0   9866.0   2291.0    8567.0   9172.0   \n",
       "\n",
       "      E_AGE17  E_DISABL  E_SNGPNT  E_MINRTY  E_LIMENG  E_MUNIT  E_MOBILE  \\\n",
       "1001  14214.0    8700.0    1649.0   13103.0     249.0    842.0    4401.0   \n",
       "1003  43186.0   26603.0    5027.0   32158.0    2571.0  18988.0   12200.0   \n",
       "1005   5862.0    4856.0    1098.0   14614.0     549.0    129.0    3175.0   \n",
       "1007   4903.0    3343.0     637.0    5717.0     112.0    163.0    2379.0   \n",
       "1009  13877.0    9729.0    1650.0    6825.0     954.0    215.0    5497.0   \n",
       "\n",
       "      E_CROWD  E_NOVEH  E_GROUPQ  E_UNINSUR  E_DAYPOP  Deaths  \n",
       "1001    530.0   1081.0     442.0     5814.0   43534.0   114.0  \n",
       "1003    998.0   2242.0    2611.0    27758.0  177010.0   465.0  \n",
       "1005    178.0    802.0    2869.0     3760.0   29769.0    90.0  \n",
       "1007     17.0    299.0    1576.0     2725.0   19274.0    57.0  \n",
       "1009    344.0    823.0     572.0     6922.0   41857.0   143.0  "
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "svi_mortality_2014.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Deaths</th>\n",
       "      <th>E_AGE17</th>\n",
       "      <th>E_AGE65</th>\n",
       "      <th>E_CROWD</th>\n",
       "      <th>E_DAYPOP</th>\n",
       "      <th>E_DISABL</th>\n",
       "      <th>E_GROUPQ</th>\n",
       "      <th>E_HH</th>\n",
       "      <th>E_HU</th>\n",
       "      <th>E_LIMENG</th>\n",
       "      <th>E_MINRTY</th>\n",
       "      <th>E_MOBILE</th>\n",
       "      <th>E_MUNIT</th>\n",
       "      <th>E_NOHSDP</th>\n",
       "      <th>E_NOVEH</th>\n",
       "      <th>E_POV</th>\n",
       "      <th>E_SNGPNT</th>\n",
       "      <th>E_TOTPOP</th>\n",
       "      <th>E_UNEMP</th>\n",
       "      <th>E_UNINSUR</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1001</th>\n",
       "      <td>41.0</td>\n",
       "      <td>-1071.0</td>\n",
       "      <td>1169.0</td>\n",
       "      <td>-191.0</td>\n",
       "      <td>-1724.0</td>\n",
       "      <td>958.0</td>\n",
       "      <td>136.0</td>\n",
       "      <td>1255.0</td>\n",
       "      <td>1266.0</td>\n",
       "      <td>114.0</td>\n",
       "      <td>1376.0</td>\n",
       "      <td>-88.0</td>\n",
       "      <td>76.0</td>\n",
       "      <td>-739.0</td>\n",
       "      <td>86.0</td>\n",
       "      <td>5605.0</td>\n",
       "      <td>-41.0</td>\n",
       "      <td>503.0</td>\n",
       "      <td>-1516.0</td>\n",
       "      <td>-1469.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1003</th>\n",
       "      <td>119.0</td>\n",
       "      <td>3807.0</td>\n",
       "      <td>10934.0</td>\n",
       "      <td>282.0</td>\n",
       "      <td>41597.0</td>\n",
       "      <td>4012.0</td>\n",
       "      <td>343.0</td>\n",
       "      <td>10989.0</td>\n",
       "      <td>11184.0</td>\n",
       "      <td>-978.0</td>\n",
       "      <td>5176.0</td>\n",
       "      <td>-307.0</td>\n",
       "      <td>525.0</td>\n",
       "      <td>208.0</td>\n",
       "      <td>385.0</td>\n",
       "      <td>10425.0</td>\n",
       "      <td>-1710.0</td>\n",
       "      <td>27084.0</td>\n",
       "      <td>-3829.0</td>\n",
       "      <td>-7257.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1005</th>\n",
       "      <td>16.0</td>\n",
       "      <td>-640.0</td>\n",
       "      <td>597.0</td>\n",
       "      <td>172.0</td>\n",
       "      <td>-2636.0</td>\n",
       "      <td>-697.0</td>\n",
       "      <td>41.0</td>\n",
       "      <td>177.0</td>\n",
       "      <td>224.0</td>\n",
       "      <td>-116.0</td>\n",
       "      <td>-920.0</td>\n",
       "      <td>469.0</td>\n",
       "      <td>41.0</td>\n",
       "      <td>-293.0</td>\n",
       "      <td>237.0</td>\n",
       "      <td>3133.0</td>\n",
       "      <td>-69.0</td>\n",
       "      <td>-2093.0</td>\n",
       "      <td>-878.0</td>\n",
       "      <td>-1398.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1007</th>\n",
       "      <td>21.0</td>\n",
       "      <td>-319.0</td>\n",
       "      <td>467.0</td>\n",
       "      <td>74.0</td>\n",
       "      <td>-475.0</td>\n",
       "      <td>405.0</td>\n",
       "      <td>81.0</td>\n",
       "      <td>181.0</td>\n",
       "      <td>252.0</td>\n",
       "      <td>-37.0</td>\n",
       "      <td>7.0</td>\n",
       "      <td>564.0</td>\n",
       "      <td>65.0</td>\n",
       "      <td>-410.0</td>\n",
       "      <td>182.0</td>\n",
       "      <td>2134.0</td>\n",
       "      <td>153.0</td>\n",
       "      <td>-279.0</td>\n",
       "      <td>-308.0</td>\n",
       "      <td>-847.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1009</th>\n",
       "      <td>55.0</td>\n",
       "      <td>-505.0</td>\n",
       "      <td>1210.0</td>\n",
       "      <td>41.0</td>\n",
       "      <td>315.0</td>\n",
       "      <td>-1165.0</td>\n",
       "      <td>-8.0</td>\n",
       "      <td>271.0</td>\n",
       "      <td>536.0</td>\n",
       "      <td>-153.0</td>\n",
       "      <td>865.0</td>\n",
       "      <td>546.0</td>\n",
       "      <td>-48.0</td>\n",
       "      <td>-1729.0</td>\n",
       "      <td>254.0</td>\n",
       "      <td>3758.0</td>\n",
       "      <td>-337.0</td>\n",
       "      <td>110.0</td>\n",
       "      <td>-1038.0</td>\n",
       "      <td>-1176.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "      Deaths  E_AGE17  E_AGE65  E_CROWD  E_DAYPOP  E_DISABL  E_GROUPQ  \\\n",
       "1001    41.0  -1071.0   1169.0   -191.0   -1724.0     958.0     136.0   \n",
       "1003   119.0   3807.0  10934.0    282.0   41597.0    4012.0     343.0   \n",
       "1005    16.0   -640.0    597.0    172.0   -2636.0    -697.0      41.0   \n",
       "1007    21.0   -319.0    467.0     74.0    -475.0     405.0      81.0   \n",
       "1009    55.0   -505.0   1210.0     41.0     315.0   -1165.0      -8.0   \n",
       "\n",
       "         E_HH     E_HU  E_LIMENG  E_MINRTY  E_MOBILE  E_MUNIT  E_NOHSDP  \\\n",
       "1001   1255.0   1266.0     114.0    1376.0     -88.0     76.0    -739.0   \n",
       "1003  10989.0  11184.0    -978.0    5176.0    -307.0    525.0     208.0   \n",
       "1005    177.0    224.0    -116.0    -920.0     469.0     41.0    -293.0   \n",
       "1007    181.0    252.0     -37.0       7.0     564.0     65.0    -410.0   \n",
       "1009    271.0    536.0    -153.0     865.0     546.0    -48.0   -1729.0   \n",
       "\n",
       "      E_NOVEH    E_POV  E_SNGPNT  E_TOTPOP  E_UNEMP  E_UNINSUR  \n",
       "1001     86.0   5605.0     -41.0     503.0  -1516.0    -1469.0  \n",
       "1003    385.0  10425.0   -1710.0   27084.0  -3829.0    -7257.0  \n",
       "1005    237.0   3133.0     -69.0   -2093.0   -878.0    -1398.0  \n",
       "1007    182.0   2134.0     153.0    -279.0   -308.0     -847.0  \n",
       "1009    254.0   3758.0    -337.0     110.0  -1038.0    -1176.0  "
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "diff_2020_2014.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [],
   "source": [
    "pd.set_option('display.max_columns', None)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "diff_2020_2014 = diff_2020_2014.add_prefix('diff_')\n",
    "ml_df = pd.concat([svi_mortality_2014, diff_2020_2014], axis=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>E_TOTPOP</th>\n",
       "      <th>E_HU</th>\n",
       "      <th>E_HH</th>\n",
       "      <th>E_POV</th>\n",
       "      <th>E_UNEMP</th>\n",
       "      <th>E_NOHSDP</th>\n",
       "      <th>E_AGE65</th>\n",
       "      <th>E_AGE17</th>\n",
       "      <th>E_DISABL</th>\n",
       "      <th>E_SNGPNT</th>\n",
       "      <th>E_MINRTY</th>\n",
       "      <th>E_LIMENG</th>\n",
       "      <th>E_MUNIT</th>\n",
       "      <th>E_MOBILE</th>\n",
       "      <th>E_CROWD</th>\n",
       "      <th>E_NOVEH</th>\n",
       "      <th>E_GROUPQ</th>\n",
       "      <th>E_UNINSUR</th>\n",
       "      <th>E_DAYPOP</th>\n",
       "      <th>Deaths</th>\n",
       "      <th>diff_Deaths</th>\n",
       "      <th>diff_E_AGE17</th>\n",
       "      <th>diff_E_AGE65</th>\n",
       "      <th>diff_E_CROWD</th>\n",
       "      <th>diff_E_DAYPOP</th>\n",
       "      <th>diff_E_DISABL</th>\n",
       "      <th>diff_E_GROUPQ</th>\n",
       "      <th>diff_E_HH</th>\n",
       "      <th>diff_E_HU</th>\n",
       "      <th>diff_E_LIMENG</th>\n",
       "      <th>diff_E_MINRTY</th>\n",
       "      <th>diff_E_MOBILE</th>\n",
       "      <th>diff_E_MUNIT</th>\n",
       "      <th>diff_E_NOHSDP</th>\n",
       "      <th>diff_E_NOVEH</th>\n",
       "      <th>diff_E_POV</th>\n",
       "      <th>diff_E_SNGPNT</th>\n",
       "      <th>diff_E_TOTPOP</th>\n",
       "      <th>diff_E_UNEMP</th>\n",
       "      <th>diff_E_UNINSUR</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1001</th>\n",
       "      <td>55136.0</td>\n",
       "      <td>22431.0</td>\n",
       "      <td>20304.0</td>\n",
       "      <td>7006.0</td>\n",
       "      <td>2252.0</td>\n",
       "      <td>5012.0</td>\n",
       "      <td>7321.0</td>\n",
       "      <td>14214.0</td>\n",
       "      <td>8700.0</td>\n",
       "      <td>1649.0</td>\n",
       "      <td>13103.0</td>\n",
       "      <td>249.0</td>\n",
       "      <td>842.0</td>\n",
       "      <td>4401.0</td>\n",
       "      <td>530.0</td>\n",
       "      <td>1081.0</td>\n",
       "      <td>442.0</td>\n",
       "      <td>5814.0</td>\n",
       "      <td>43534.0</td>\n",
       "      <td>114.0</td>\n",
       "      <td>41.0</td>\n",
       "      <td>-1071.0</td>\n",
       "      <td>1169.0</td>\n",
       "      <td>-191.0</td>\n",
       "      <td>-1724.0</td>\n",
       "      <td>958.0</td>\n",
       "      <td>136.0</td>\n",
       "      <td>1255.0</td>\n",
       "      <td>1266.0</td>\n",
       "      <td>114.0</td>\n",
       "      <td>1376.0</td>\n",
       "      <td>-88.0</td>\n",
       "      <td>76.0</td>\n",
       "      <td>-739.0</td>\n",
       "      <td>86.0</td>\n",
       "      <td>5605.0</td>\n",
       "      <td>-41.0</td>\n",
       "      <td>503.0</td>\n",
       "      <td>-1516.0</td>\n",
       "      <td>-1469.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1003</th>\n",
       "      <td>191205.0</td>\n",
       "      <td>105563.0</td>\n",
       "      <td>73058.0</td>\n",
       "      <td>25988.0</td>\n",
       "      <td>7856.0</td>\n",
       "      <td>14615.0</td>\n",
       "      <td>33782.0</td>\n",
       "      <td>43186.0</td>\n",
       "      <td>26603.0</td>\n",
       "      <td>5027.0</td>\n",
       "      <td>32158.0</td>\n",
       "      <td>2571.0</td>\n",
       "      <td>18988.0</td>\n",
       "      <td>12200.0</td>\n",
       "      <td>998.0</td>\n",
       "      <td>2242.0</td>\n",
       "      <td>2611.0</td>\n",
       "      <td>27758.0</td>\n",
       "      <td>177010.0</td>\n",
       "      <td>465.0</td>\n",
       "      <td>119.0</td>\n",
       "      <td>3807.0</td>\n",
       "      <td>10934.0</td>\n",
       "      <td>282.0</td>\n",
       "      <td>41597.0</td>\n",
       "      <td>4012.0</td>\n",
       "      <td>343.0</td>\n",
       "      <td>10989.0</td>\n",
       "      <td>11184.0</td>\n",
       "      <td>-978.0</td>\n",
       "      <td>5176.0</td>\n",
       "      <td>-307.0</td>\n",
       "      <td>525.0</td>\n",
       "      <td>208.0</td>\n",
       "      <td>385.0</td>\n",
       "      <td>10425.0</td>\n",
       "      <td>-1710.0</td>\n",
       "      <td>27084.0</td>\n",
       "      <td>-3829.0</td>\n",
       "      <td>-7257.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1005</th>\n",
       "      <td>27119.0</td>\n",
       "      <td>11833.0</td>\n",
       "      <td>9145.0</td>\n",
       "      <td>5832.0</td>\n",
       "      <td>1527.0</td>\n",
       "      <td>4790.0</td>\n",
       "      <td>4180.0</td>\n",
       "      <td>5862.0</td>\n",
       "      <td>4856.0</td>\n",
       "      <td>1098.0</td>\n",
       "      <td>14614.0</td>\n",
       "      <td>549.0</td>\n",
       "      <td>129.0</td>\n",
       "      <td>3175.0</td>\n",
       "      <td>178.0</td>\n",
       "      <td>802.0</td>\n",
       "      <td>2869.0</td>\n",
       "      <td>3760.0</td>\n",
       "      <td>29769.0</td>\n",
       "      <td>90.0</td>\n",
       "      <td>16.0</td>\n",
       "      <td>-640.0</td>\n",
       "      <td>597.0</td>\n",
       "      <td>172.0</td>\n",
       "      <td>-2636.0</td>\n",
       "      <td>-697.0</td>\n",
       "      <td>41.0</td>\n",
       "      <td>177.0</td>\n",
       "      <td>224.0</td>\n",
       "      <td>-116.0</td>\n",
       "      <td>-920.0</td>\n",
       "      <td>469.0</td>\n",
       "      <td>41.0</td>\n",
       "      <td>-293.0</td>\n",
       "      <td>237.0</td>\n",
       "      <td>3133.0</td>\n",
       "      <td>-69.0</td>\n",
       "      <td>-2093.0</td>\n",
       "      <td>-878.0</td>\n",
       "      <td>-1398.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1007</th>\n",
       "      <td>22653.0</td>\n",
       "      <td>8985.0</td>\n",
       "      <td>7078.0</td>\n",
       "      <td>3596.0</td>\n",
       "      <td>975.0</td>\n",
       "      <td>3466.0</td>\n",
       "      <td>3209.0</td>\n",
       "      <td>4903.0</td>\n",
       "      <td>3343.0</td>\n",
       "      <td>637.0</td>\n",
       "      <td>5717.0</td>\n",
       "      <td>112.0</td>\n",
       "      <td>163.0</td>\n",
       "      <td>2379.0</td>\n",
       "      <td>17.0</td>\n",
       "      <td>299.0</td>\n",
       "      <td>1576.0</td>\n",
       "      <td>2725.0</td>\n",
       "      <td>19274.0</td>\n",
       "      <td>57.0</td>\n",
       "      <td>21.0</td>\n",
       "      <td>-319.0</td>\n",
       "      <td>467.0</td>\n",
       "      <td>74.0</td>\n",
       "      <td>-475.0</td>\n",
       "      <td>405.0</td>\n",
       "      <td>81.0</td>\n",
       "      <td>181.0</td>\n",
       "      <td>252.0</td>\n",
       "      <td>-37.0</td>\n",
       "      <td>7.0</td>\n",
       "      <td>564.0</td>\n",
       "      <td>65.0</td>\n",
       "      <td>-410.0</td>\n",
       "      <td>182.0</td>\n",
       "      <td>2134.0</td>\n",
       "      <td>153.0</td>\n",
       "      <td>-279.0</td>\n",
       "      <td>-308.0</td>\n",
       "      <td>-847.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1009</th>\n",
       "      <td>57645.0</td>\n",
       "      <td>23868.0</td>\n",
       "      <td>20934.0</td>\n",
       "      <td>9866.0</td>\n",
       "      <td>2291.0</td>\n",
       "      <td>8567.0</td>\n",
       "      <td>9172.0</td>\n",
       "      <td>13877.0</td>\n",
       "      <td>9729.0</td>\n",
       "      <td>1650.0</td>\n",
       "      <td>6825.0</td>\n",
       "      <td>954.0</td>\n",
       "      <td>215.0</td>\n",
       "      <td>5497.0</td>\n",
       "      <td>344.0</td>\n",
       "      <td>823.0</td>\n",
       "      <td>572.0</td>\n",
       "      <td>6922.0</td>\n",
       "      <td>41857.0</td>\n",
       "      <td>143.0</td>\n",
       "      <td>55.0</td>\n",
       "      <td>-505.0</td>\n",
       "      <td>1210.0</td>\n",
       "      <td>41.0</td>\n",
       "      <td>315.0</td>\n",
       "      <td>-1165.0</td>\n",
       "      <td>-8.0</td>\n",
       "      <td>271.0</td>\n",
       "      <td>536.0</td>\n",
       "      <td>-153.0</td>\n",
       "      <td>865.0</td>\n",
       "      <td>546.0</td>\n",
       "      <td>-48.0</td>\n",
       "      <td>-1729.0</td>\n",
       "      <td>254.0</td>\n",
       "      <td>3758.0</td>\n",
       "      <td>-337.0</td>\n",
       "      <td>110.0</td>\n",
       "      <td>-1038.0</td>\n",
       "      <td>-1176.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "      E_TOTPOP      E_HU     E_HH    E_POV  E_UNEMP  E_NOHSDP  E_AGE65  \\\n",
       "1001   55136.0   22431.0  20304.0   7006.0   2252.0    5012.0   7321.0   \n",
       "1003  191205.0  105563.0  73058.0  25988.0   7856.0   14615.0  33782.0   \n",
       "1005   27119.0   11833.0   9145.0   5832.0   1527.0    4790.0   4180.0   \n",
       "1007   22653.0    8985.0   7078.0   3596.0    975.0    3466.0   3209.0   \n",
       "1009   57645.0   23868.0  20934.0   9866.0   2291.0    8567.0   9172.0   \n",
       "\n",
       "      E_AGE17  E_DISABL  E_SNGPNT  E_MINRTY  E_LIMENG  E_MUNIT  E_MOBILE  \\\n",
       "1001  14214.0    8700.0    1649.0   13103.0     249.0    842.0    4401.0   \n",
       "1003  43186.0   26603.0    5027.0   32158.0    2571.0  18988.0   12200.0   \n",
       "1005   5862.0    4856.0    1098.0   14614.0     549.0    129.0    3175.0   \n",
       "1007   4903.0    3343.0     637.0    5717.0     112.0    163.0    2379.0   \n",
       "1009  13877.0    9729.0    1650.0    6825.0     954.0    215.0    5497.0   \n",
       "\n",
       "      E_CROWD  E_NOVEH  E_GROUPQ  E_UNINSUR  E_DAYPOP  Deaths  diff_Deaths  \\\n",
       "1001    530.0   1081.0     442.0     5814.0   43534.0   114.0         41.0   \n",
       "1003    998.0   2242.0    2611.0    27758.0  177010.0   465.0        119.0   \n",
       "1005    178.0    802.0    2869.0     3760.0   29769.0    90.0         16.0   \n",
       "1007     17.0    299.0    1576.0     2725.0   19274.0    57.0         21.0   \n",
       "1009    344.0    823.0     572.0     6922.0   41857.0   143.0         55.0   \n",
       "\n",
       "      diff_E_AGE17  diff_E_AGE65  diff_E_CROWD  diff_E_DAYPOP  diff_E_DISABL  \\\n",
       "1001       -1071.0        1169.0        -191.0        -1724.0          958.0   \n",
       "1003        3807.0       10934.0         282.0        41597.0         4012.0   \n",
       "1005        -640.0         597.0         172.0        -2636.0         -697.0   \n",
       "1007        -319.0         467.0          74.0         -475.0          405.0   \n",
       "1009        -505.0        1210.0          41.0          315.0        -1165.0   \n",
       "\n",
       "      diff_E_GROUPQ  diff_E_HH  diff_E_HU  diff_E_LIMENG  diff_E_MINRTY  \\\n",
       "1001          136.0     1255.0     1266.0          114.0         1376.0   \n",
       "1003          343.0    10989.0    11184.0         -978.0         5176.0   \n",
       "1005           41.0      177.0      224.0         -116.0         -920.0   \n",
       "1007           81.0      181.0      252.0          -37.0            7.0   \n",
       "1009           -8.0      271.0      536.0         -153.0          865.0   \n",
       "\n",
       "      diff_E_MOBILE  diff_E_MUNIT  diff_E_NOHSDP  diff_E_NOVEH  diff_E_POV  \\\n",
       "1001          -88.0          76.0         -739.0          86.0      5605.0   \n",
       "1003         -307.0         525.0          208.0         385.0     10425.0   \n",
       "1005          469.0          41.0         -293.0         237.0      3133.0   \n",
       "1007          564.0          65.0         -410.0         182.0      2134.0   \n",
       "1009          546.0         -48.0        -1729.0         254.0      3758.0   \n",
       "\n",
       "      diff_E_SNGPNT  diff_E_TOTPOP  diff_E_UNEMP  diff_E_UNINSUR  \n",
       "1001          -41.0          503.0       -1516.0         -1469.0  \n",
       "1003        -1710.0        27084.0       -3829.0         -7257.0  \n",
       "1005          -69.0        -2093.0        -878.0         -1398.0  \n",
       "1007          153.0         -279.0        -308.0          -847.0  \n",
       "1009         -337.0          110.0       -1038.0         -1176.0  "
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "ml_df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [],
   "source": [
    "ml_df.dropna(inplace=True)\n",
    "y = ml_df.diff_Deaths\n",
    "ml_df.drop('diff_Deaths', axis=1, inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "1001      41.0\n",
       "1003     119.0\n",
       "1005      16.0\n",
       "1007      21.0\n",
       "1009      55.0\n",
       "         ...  \n",
       "56037     33.0\n",
       "56039      4.0\n",
       "56041     11.0\n",
       "56043      6.0\n",
       "56045      4.0\n",
       "Name: diff_Deaths, Length: 2847, dtype: float64"
      ]
     },
     "execution_count": 33,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "y"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Index(['E_TOTPOP', 'E_HU', 'E_HH', 'E_POV', 'E_UNEMP', 'E_NOHSDP', 'E_AGE65',\n",
       "       'E_AGE17', 'E_DISABL', 'E_SNGPNT', 'E_MINRTY', 'E_LIMENG', 'E_MUNIT',\n",
       "       'E_MOBILE', 'E_CROWD', 'E_NOVEH', 'E_GROUPQ', 'E_UNINSUR', 'E_DAYPOP',\n",
       "       'Deaths', 'diff_E_AGE17', 'diff_E_AGE65', 'diff_E_CROWD',\n",
       "       'diff_E_DAYPOP', 'diff_E_DISABL', 'diff_E_GROUPQ', 'diff_E_HH',\n",
       "       'diff_E_HU', 'diff_E_LIMENG', 'diff_E_MINRTY', 'diff_E_MOBILE',\n",
       "       'diff_E_MUNIT', 'diff_E_NOHSDP', 'diff_E_NOVEH', 'diff_E_POV',\n",
       "       'diff_E_SNGPNT', 'diff_E_TOTPOP', 'diff_E_UNEMP', 'diff_E_UNINSUR'],\n",
       "      dtype='object')"
      ]
     },
     "execution_count": 22,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "ml_df.columns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>E_TOTPOP</th>\n",
       "      <th>E_HU</th>\n",
       "      <th>E_HH</th>\n",
       "      <th>E_POV</th>\n",
       "      <th>E_UNEMP</th>\n",
       "      <th>E_NOHSDP</th>\n",
       "      <th>E_AGE65</th>\n",
       "      <th>E_AGE17</th>\n",
       "      <th>E_DISABL</th>\n",
       "      <th>E_SNGPNT</th>\n",
       "      <th>E_MINRTY</th>\n",
       "      <th>E_LIMENG</th>\n",
       "      <th>E_MUNIT</th>\n",
       "      <th>E_MOBILE</th>\n",
       "      <th>E_CROWD</th>\n",
       "      <th>E_NOVEH</th>\n",
       "      <th>E_GROUPQ</th>\n",
       "      <th>E_UNINSUR</th>\n",
       "      <th>E_DAYPOP</th>\n",
       "      <th>Deaths</th>\n",
       "      <th>diff_E_AGE17</th>\n",
       "      <th>diff_E_AGE65</th>\n",
       "      <th>diff_E_CROWD</th>\n",
       "      <th>diff_E_DAYPOP</th>\n",
       "      <th>diff_E_DISABL</th>\n",
       "      <th>diff_E_GROUPQ</th>\n",
       "      <th>diff_E_HH</th>\n",
       "      <th>diff_E_HU</th>\n",
       "      <th>diff_E_LIMENG</th>\n",
       "      <th>diff_E_MINRTY</th>\n",
       "      <th>diff_E_MOBILE</th>\n",
       "      <th>diff_E_MUNIT</th>\n",
       "      <th>diff_E_NOHSDP</th>\n",
       "      <th>diff_E_NOVEH</th>\n",
       "      <th>diff_E_POV</th>\n",
       "      <th>diff_E_SNGPNT</th>\n",
       "      <th>diff_E_TOTPOP</th>\n",
       "      <th>diff_E_UNEMP</th>\n",
       "      <th>diff_E_UNINSUR</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1001</th>\n",
       "      <td>55136.0</td>\n",
       "      <td>22431.0</td>\n",
       "      <td>20304.0</td>\n",
       "      <td>7006.0</td>\n",
       "      <td>2252.0</td>\n",
       "      <td>5012.0</td>\n",
       "      <td>7321.0</td>\n",
       "      <td>14214.0</td>\n",
       "      <td>8700.0</td>\n",
       "      <td>1649.0</td>\n",
       "      <td>13103.0</td>\n",
       "      <td>249.0</td>\n",
       "      <td>842.0</td>\n",
       "      <td>4401.0</td>\n",
       "      <td>530.0</td>\n",
       "      <td>1081.0</td>\n",
       "      <td>442.0</td>\n",
       "      <td>5814.0</td>\n",
       "      <td>43534.0</td>\n",
       "      <td>114.0</td>\n",
       "      <td>-1071.0</td>\n",
       "      <td>1169.0</td>\n",
       "      <td>-191.0</td>\n",
       "      <td>-1724.0</td>\n",
       "      <td>958.0</td>\n",
       "      <td>136.0</td>\n",
       "      <td>1255.0</td>\n",
       "      <td>1266.0</td>\n",
       "      <td>114.0</td>\n",
       "      <td>1376.0</td>\n",
       "      <td>-88.0</td>\n",
       "      <td>76.0</td>\n",
       "      <td>-739.0</td>\n",
       "      <td>86.0</td>\n",
       "      <td>5605.0</td>\n",
       "      <td>-41.0</td>\n",
       "      <td>503.0</td>\n",
       "      <td>-1516.0</td>\n",
       "      <td>-1469.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1003</th>\n",
       "      <td>191205.0</td>\n",
       "      <td>105563.0</td>\n",
       "      <td>73058.0</td>\n",
       "      <td>25988.0</td>\n",
       "      <td>7856.0</td>\n",
       "      <td>14615.0</td>\n",
       "      <td>33782.0</td>\n",
       "      <td>43186.0</td>\n",
       "      <td>26603.0</td>\n",
       "      <td>5027.0</td>\n",
       "      <td>32158.0</td>\n",
       "      <td>2571.0</td>\n",
       "      <td>18988.0</td>\n",
       "      <td>12200.0</td>\n",
       "      <td>998.0</td>\n",
       "      <td>2242.0</td>\n",
       "      <td>2611.0</td>\n",
       "      <td>27758.0</td>\n",
       "      <td>177010.0</td>\n",
       "      <td>465.0</td>\n",
       "      <td>3807.0</td>\n",
       "      <td>10934.0</td>\n",
       "      <td>282.0</td>\n",
       "      <td>41597.0</td>\n",
       "      <td>4012.0</td>\n",
       "      <td>343.0</td>\n",
       "      <td>10989.0</td>\n",
       "      <td>11184.0</td>\n",
       "      <td>-978.0</td>\n",
       "      <td>5176.0</td>\n",
       "      <td>-307.0</td>\n",
       "      <td>525.0</td>\n",
       "      <td>208.0</td>\n",
       "      <td>385.0</td>\n",
       "      <td>10425.0</td>\n",
       "      <td>-1710.0</td>\n",
       "      <td>27084.0</td>\n",
       "      <td>-3829.0</td>\n",
       "      <td>-7257.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1005</th>\n",
       "      <td>27119.0</td>\n",
       "      <td>11833.0</td>\n",
       "      <td>9145.0</td>\n",
       "      <td>5832.0</td>\n",
       "      <td>1527.0</td>\n",
       "      <td>4790.0</td>\n",
       "      <td>4180.0</td>\n",
       "      <td>5862.0</td>\n",
       "      <td>4856.0</td>\n",
       "      <td>1098.0</td>\n",
       "      <td>14614.0</td>\n",
       "      <td>549.0</td>\n",
       "      <td>129.0</td>\n",
       "      <td>3175.0</td>\n",
       "      <td>178.0</td>\n",
       "      <td>802.0</td>\n",
       "      <td>2869.0</td>\n",
       "      <td>3760.0</td>\n",
       "      <td>29769.0</td>\n",
       "      <td>90.0</td>\n",
       "      <td>-640.0</td>\n",
       "      <td>597.0</td>\n",
       "      <td>172.0</td>\n",
       "      <td>-2636.0</td>\n",
       "      <td>-697.0</td>\n",
       "      <td>41.0</td>\n",
       "      <td>177.0</td>\n",
       "      <td>224.0</td>\n",
       "      <td>-116.0</td>\n",
       "      <td>-920.0</td>\n",
       "      <td>469.0</td>\n",
       "      <td>41.0</td>\n",
       "      <td>-293.0</td>\n",
       "      <td>237.0</td>\n",
       "      <td>3133.0</td>\n",
       "      <td>-69.0</td>\n",
       "      <td>-2093.0</td>\n",
       "      <td>-878.0</td>\n",
       "      <td>-1398.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1007</th>\n",
       "      <td>22653.0</td>\n",
       "      <td>8985.0</td>\n",
       "      <td>7078.0</td>\n",
       "      <td>3596.0</td>\n",
       "      <td>975.0</td>\n",
       "      <td>3466.0</td>\n",
       "      <td>3209.0</td>\n",
       "      <td>4903.0</td>\n",
       "      <td>3343.0</td>\n",
       "      <td>637.0</td>\n",
       "      <td>5717.0</td>\n",
       "      <td>112.0</td>\n",
       "      <td>163.0</td>\n",
       "      <td>2379.0</td>\n",
       "      <td>17.0</td>\n",
       "      <td>299.0</td>\n",
       "      <td>1576.0</td>\n",
       "      <td>2725.0</td>\n",
       "      <td>19274.0</td>\n",
       "      <td>57.0</td>\n",
       "      <td>-319.0</td>\n",
       "      <td>467.0</td>\n",
       "      <td>74.0</td>\n",
       "      <td>-475.0</td>\n",
       "      <td>405.0</td>\n",
       "      <td>81.0</td>\n",
       "      <td>181.0</td>\n",
       "      <td>252.0</td>\n",
       "      <td>-37.0</td>\n",
       "      <td>7.0</td>\n",
       "      <td>564.0</td>\n",
       "      <td>65.0</td>\n",
       "      <td>-410.0</td>\n",
       "      <td>182.0</td>\n",
       "      <td>2134.0</td>\n",
       "      <td>153.0</td>\n",
       "      <td>-279.0</td>\n",
       "      <td>-308.0</td>\n",
       "      <td>-847.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1009</th>\n",
       "      <td>57645.0</td>\n",
       "      <td>23868.0</td>\n",
       "      <td>20934.0</td>\n",
       "      <td>9866.0</td>\n",
       "      <td>2291.0</td>\n",
       "      <td>8567.0</td>\n",
       "      <td>9172.0</td>\n",
       "      <td>13877.0</td>\n",
       "      <td>9729.0</td>\n",
       "      <td>1650.0</td>\n",
       "      <td>6825.0</td>\n",
       "      <td>954.0</td>\n",
       "      <td>215.0</td>\n",
       "      <td>5497.0</td>\n",
       "      <td>344.0</td>\n",
       "      <td>823.0</td>\n",
       "      <td>572.0</td>\n",
       "      <td>6922.0</td>\n",
       "      <td>41857.0</td>\n",
       "      <td>143.0</td>\n",
       "      <td>-505.0</td>\n",
       "      <td>1210.0</td>\n",
       "      <td>41.0</td>\n",
       "      <td>315.0</td>\n",
       "      <td>-1165.0</td>\n",
       "      <td>-8.0</td>\n",
       "      <td>271.0</td>\n",
       "      <td>536.0</td>\n",
       "      <td>-153.0</td>\n",
       "      <td>865.0</td>\n",
       "      <td>546.0</td>\n",
       "      <td>-48.0</td>\n",
       "      <td>-1729.0</td>\n",
       "      <td>254.0</td>\n",
       "      <td>3758.0</td>\n",
       "      <td>-337.0</td>\n",
       "      <td>110.0</td>\n",
       "      <td>-1038.0</td>\n",
       "      <td>-1176.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "      E_TOTPOP      E_HU     E_HH    E_POV  E_UNEMP  E_NOHSDP  E_AGE65  \\\n",
       "1001   55136.0   22431.0  20304.0   7006.0   2252.0    5012.0   7321.0   \n",
       "1003  191205.0  105563.0  73058.0  25988.0   7856.0   14615.0  33782.0   \n",
       "1005   27119.0   11833.0   9145.0   5832.0   1527.0    4790.0   4180.0   \n",
       "1007   22653.0    8985.0   7078.0   3596.0    975.0    3466.0   3209.0   \n",
       "1009   57645.0   23868.0  20934.0   9866.0   2291.0    8567.0   9172.0   \n",
       "\n",
       "      E_AGE17  E_DISABL  E_SNGPNT  E_MINRTY  E_LIMENG  E_MUNIT  E_MOBILE  \\\n",
       "1001  14214.0    8700.0    1649.0   13103.0     249.0    842.0    4401.0   \n",
       "1003  43186.0   26603.0    5027.0   32158.0    2571.0  18988.0   12200.0   \n",
       "1005   5862.0    4856.0    1098.0   14614.0     549.0    129.0    3175.0   \n",
       "1007   4903.0    3343.0     637.0    5717.0     112.0    163.0    2379.0   \n",
       "1009  13877.0    9729.0    1650.0    6825.0     954.0    215.0    5497.0   \n",
       "\n",
       "      E_CROWD  E_NOVEH  E_GROUPQ  E_UNINSUR  E_DAYPOP  Deaths  diff_E_AGE17  \\\n",
       "1001    530.0   1081.0     442.0     5814.0   43534.0   114.0       -1071.0   \n",
       "1003    998.0   2242.0    2611.0    27758.0  177010.0   465.0        3807.0   \n",
       "1005    178.0    802.0    2869.0     3760.0   29769.0    90.0        -640.0   \n",
       "1007     17.0    299.0    1576.0     2725.0   19274.0    57.0        -319.0   \n",
       "1009    344.0    823.0     572.0     6922.0   41857.0   143.0        -505.0   \n",
       "\n",
       "      diff_E_AGE65  diff_E_CROWD  diff_E_DAYPOP  diff_E_DISABL  diff_E_GROUPQ  \\\n",
       "1001        1169.0        -191.0        -1724.0          958.0          136.0   \n",
       "1003       10934.0         282.0        41597.0         4012.0          343.0   \n",
       "1005         597.0         172.0        -2636.0         -697.0           41.0   \n",
       "1007         467.0          74.0         -475.0          405.0           81.0   \n",
       "1009        1210.0          41.0          315.0        -1165.0           -8.0   \n",
       "\n",
       "      diff_E_HH  diff_E_HU  diff_E_LIMENG  diff_E_MINRTY  diff_E_MOBILE  \\\n",
       "1001     1255.0     1266.0          114.0         1376.0          -88.0   \n",
       "1003    10989.0    11184.0         -978.0         5176.0         -307.0   \n",
       "1005      177.0      224.0         -116.0         -920.0          469.0   \n",
       "1007      181.0      252.0          -37.0            7.0          564.0   \n",
       "1009      271.0      536.0         -153.0          865.0          546.0   \n",
       "\n",
       "      diff_E_MUNIT  diff_E_NOHSDP  diff_E_NOVEH  diff_E_POV  diff_E_SNGPNT  \\\n",
       "1001          76.0         -739.0          86.0      5605.0          -41.0   \n",
       "1003         525.0          208.0         385.0     10425.0        -1710.0   \n",
       "1005          41.0         -293.0         237.0      3133.0          -69.0   \n",
       "1007          65.0         -410.0         182.0      2134.0          153.0   \n",
       "1009         -48.0        -1729.0         254.0      3758.0         -337.0   \n",
       "\n",
       "      diff_E_TOTPOP  diff_E_UNEMP  diff_E_UNINSUR  \n",
       "1001          503.0       -1516.0         -1469.0  \n",
       "1003        27084.0       -3829.0         -7257.0  \n",
       "1005        -2093.0        -878.0         -1398.0  \n",
       "1007         -279.0        -308.0          -847.0  \n",
       "1009          110.0       -1038.0         -1176.0  "
      ]
     },
     "execution_count": 23,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "ml_df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Splitting dataset for predictions\n",
    "# X = diff_2020_2014.drop('Deaths', axis=1)\n",
    "X = ml_df\n",
    "# y = diff_2020_2014.Deaths"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Scaling X learning data\n",
    "scaler = preprocessing.MinMaxScaler()\n",
    "names = X.columns\n",
    "d = scaler.fit_transform(X)\n",
    "X = pd.DataFrame(d, columns=names)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>E_TOTPOP</th>\n",
       "      <th>E_HU</th>\n",
       "      <th>E_HH</th>\n",
       "      <th>E_POV</th>\n",
       "      <th>E_UNEMP</th>\n",
       "      <th>E_NOHSDP</th>\n",
       "      <th>E_AGE65</th>\n",
       "      <th>E_AGE17</th>\n",
       "      <th>E_DISABL</th>\n",
       "      <th>E_SNGPNT</th>\n",
       "      <th>E_MINRTY</th>\n",
       "      <th>E_LIMENG</th>\n",
       "      <th>E_MUNIT</th>\n",
       "      <th>E_MOBILE</th>\n",
       "      <th>E_CROWD</th>\n",
       "      <th>E_NOVEH</th>\n",
       "      <th>E_GROUPQ</th>\n",
       "      <th>E_UNINSUR</th>\n",
       "      <th>E_DAYPOP</th>\n",
       "      <th>Deaths</th>\n",
       "      <th>diff_E_AGE17</th>\n",
       "      <th>diff_E_AGE65</th>\n",
       "      <th>diff_E_CROWD</th>\n",
       "      <th>diff_E_DAYPOP</th>\n",
       "      <th>diff_E_DISABL</th>\n",
       "      <th>diff_E_GROUPQ</th>\n",
       "      <th>diff_E_HH</th>\n",
       "      <th>diff_E_HU</th>\n",
       "      <th>diff_E_LIMENG</th>\n",
       "      <th>diff_E_MINRTY</th>\n",
       "      <th>diff_E_MOBILE</th>\n",
       "      <th>diff_E_MUNIT</th>\n",
       "      <th>diff_E_NOHSDP</th>\n",
       "      <th>diff_E_NOVEH</th>\n",
       "      <th>diff_E_POV</th>\n",
       "      <th>diff_E_SNGPNT</th>\n",
       "      <th>diff_E_TOTPOP</th>\n",
       "      <th>diff_E_UNEMP</th>\n",
       "      <th>diff_E_UNINSUR</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0.005316</td>\n",
       "      <td>0.006116</td>\n",
       "      <td>0.005990</td>\n",
       "      <td>0.003797</td>\n",
       "      <td>0.003963</td>\n",
       "      <td>0.003224</td>\n",
       "      <td>0.006096</td>\n",
       "      <td>0.005894</td>\n",
       "      <td>0.008899</td>\n",
       "      <td>0.004745</td>\n",
       "      <td>0.001800</td>\n",
       "      <td>0.000178</td>\n",
       "      <td>0.000925</td>\n",
       "      <td>0.052169</td>\n",
       "      <td>0.001356</td>\n",
       "      <td>0.001830</td>\n",
       "      <td>0.002516</td>\n",
       "      <td>0.002742</td>\n",
       "      <td>0.004180</td>\n",
       "      <td>0.006714</td>\n",
       "      <td>0.692069</td>\n",
       "      <td>0.007124</td>\n",
       "      <td>0.576842</td>\n",
       "      <td>0.096547</td>\n",
       "      <td>0.110649</td>\n",
       "      <td>0.420372</td>\n",
       "      <td>0.031711</td>\n",
       "      <td>0.024770</td>\n",
       "      <td>0.876535</td>\n",
       "      <td>0.038420</td>\n",
       "      <td>0.271194</td>\n",
       "      <td>0.051121</td>\n",
       "      <td>0.939314</td>\n",
       "      <td>0.590011</td>\n",
       "      <td>0.012150</td>\n",
       "      <td>0.996283</td>\n",
       "      <td>0.112301</td>\n",
       "      <td>0.973451</td>\n",
       "      <td>0.996829</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>0.018961</td>\n",
       "      <td>0.030137</td>\n",
       "      <td>0.022265</td>\n",
       "      <td>0.014309</td>\n",
       "      <td>0.013888</td>\n",
       "      <td>0.009541</td>\n",
       "      <td>0.029114</td>\n",
       "      <td>0.018237</td>\n",
       "      <td>0.027808</td>\n",
       "      <td>0.014532</td>\n",
       "      <td>0.004424</td>\n",
       "      <td>0.001841</td>\n",
       "      <td>0.020860</td>\n",
       "      <td>0.144617</td>\n",
       "      <td>0.002554</td>\n",
       "      <td>0.003821</td>\n",
       "      <td>0.014860</td>\n",
       "      <td>0.013371</td>\n",
       "      <td>0.017542</td>\n",
       "      <td>0.029376</td>\n",
       "      <td>0.712167</td>\n",
       "      <td>0.051380</td>\n",
       "      <td>0.593545</td>\n",
       "      <td>0.148273</td>\n",
       "      <td>0.137624</td>\n",
       "      <td>0.438211</td>\n",
       "      <td>0.086353</td>\n",
       "      <td>0.086220</td>\n",
       "      <td>0.871263</td>\n",
       "      <td>0.047066</td>\n",
       "      <td>0.247361</td>\n",
       "      <td>0.058032</td>\n",
       "      <td>0.946512</td>\n",
       "      <td>0.597397</td>\n",
       "      <td>0.021139</td>\n",
       "      <td>0.984238</td>\n",
       "      <td>0.163057</td>\n",
       "      <td>0.963419</td>\n",
       "      <td>0.991809</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>0.002506</td>\n",
       "      <td>0.003054</td>\n",
       "      <td>0.002548</td>\n",
       "      <td>0.003147</td>\n",
       "      <td>0.002680</td>\n",
       "      <td>0.003078</td>\n",
       "      <td>0.003364</td>\n",
       "      <td>0.002336</td>\n",
       "      <td>0.004839</td>\n",
       "      <td>0.003149</td>\n",
       "      <td>0.002008</td>\n",
       "      <td>0.000393</td>\n",
       "      <td>0.000142</td>\n",
       "      <td>0.037636</td>\n",
       "      <td>0.000456</td>\n",
       "      <td>0.001352</td>\n",
       "      <td>0.016329</td>\n",
       "      <td>0.001748</td>\n",
       "      <td>0.002802</td>\n",
       "      <td>0.005165</td>\n",
       "      <td>0.693845</td>\n",
       "      <td>0.004532</td>\n",
       "      <td>0.589660</td>\n",
       "      <td>0.095458</td>\n",
       "      <td>0.096031</td>\n",
       "      <td>0.412185</td>\n",
       "      <td>0.025659</td>\n",
       "      <td>0.018315</td>\n",
       "      <td>0.875425</td>\n",
       "      <td>0.033196</td>\n",
       "      <td>0.331810</td>\n",
       "      <td>0.050582</td>\n",
       "      <td>0.942704</td>\n",
       "      <td>0.593741</td>\n",
       "      <td>0.007540</td>\n",
       "      <td>0.996081</td>\n",
       "      <td>0.107344</td>\n",
       "      <td>0.976218</td>\n",
       "      <td>0.996890</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>0.002058</td>\n",
       "      <td>0.002231</td>\n",
       "      <td>0.001910</td>\n",
       "      <td>0.001908</td>\n",
       "      <td>0.001702</td>\n",
       "      <td>0.002207</td>\n",
       "      <td>0.002519</td>\n",
       "      <td>0.001927</td>\n",
       "      <td>0.003241</td>\n",
       "      <td>0.001814</td>\n",
       "      <td>0.000783</td>\n",
       "      <td>0.000080</td>\n",
       "      <td>0.000179</td>\n",
       "      <td>0.028200</td>\n",
       "      <td>0.000044</td>\n",
       "      <td>0.000489</td>\n",
       "      <td>0.008970</td>\n",
       "      <td>0.001246</td>\n",
       "      <td>0.001752</td>\n",
       "      <td>0.003034</td>\n",
       "      <td>0.695167</td>\n",
       "      <td>0.003943</td>\n",
       "      <td>0.586200</td>\n",
       "      <td>0.098038</td>\n",
       "      <td>0.105764</td>\n",
       "      <td>0.415633</td>\n",
       "      <td>0.025682</td>\n",
       "      <td>0.018488</td>\n",
       "      <td>0.875806</td>\n",
       "      <td>0.035305</td>\n",
       "      <td>0.342148</td>\n",
       "      <td>0.050951</td>\n",
       "      <td>0.941815</td>\n",
       "      <td>0.592382</td>\n",
       "      <td>0.005677</td>\n",
       "      <td>0.997683</td>\n",
       "      <td>0.110808</td>\n",
       "      <td>0.978690</td>\n",
       "      <td>0.997368</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>0.005567</td>\n",
       "      <td>0.006531</td>\n",
       "      <td>0.006185</td>\n",
       "      <td>0.005381</td>\n",
       "      <td>0.004033</td>\n",
       "      <td>0.005563</td>\n",
       "      <td>0.007706</td>\n",
       "      <td>0.005751</td>\n",
       "      <td>0.009986</td>\n",
       "      <td>0.004748</td>\n",
       "      <td>0.000936</td>\n",
       "      <td>0.000683</td>\n",
       "      <td>0.000236</td>\n",
       "      <td>0.065160</td>\n",
       "      <td>0.000880</td>\n",
       "      <td>0.001388</td>\n",
       "      <td>0.003256</td>\n",
       "      <td>0.003279</td>\n",
       "      <td>0.004012</td>\n",
       "      <td>0.008587</td>\n",
       "      <td>0.694401</td>\n",
       "      <td>0.007310</td>\n",
       "      <td>0.585034</td>\n",
       "      <td>0.098982</td>\n",
       "      <td>0.091897</td>\n",
       "      <td>0.407963</td>\n",
       "      <td>0.026187</td>\n",
       "      <td>0.020248</td>\n",
       "      <td>0.875246</td>\n",
       "      <td>0.037257</td>\n",
       "      <td>0.340189</td>\n",
       "      <td>0.049212</td>\n",
       "      <td>0.931791</td>\n",
       "      <td>0.594161</td>\n",
       "      <td>0.008705</td>\n",
       "      <td>0.994147</td>\n",
       "      <td>0.111551</td>\n",
       "      <td>0.975524</td>\n",
       "      <td>0.997083</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   E_TOTPOP      E_HU      E_HH     E_POV   E_UNEMP  E_NOHSDP   E_AGE65  \\\n",
       "0  0.005316  0.006116  0.005990  0.003797  0.003963  0.003224  0.006096   \n",
       "1  0.018961  0.030137  0.022265  0.014309  0.013888  0.009541  0.029114   \n",
       "2  0.002506  0.003054  0.002548  0.003147  0.002680  0.003078  0.003364   \n",
       "3  0.002058  0.002231  0.001910  0.001908  0.001702  0.002207  0.002519   \n",
       "4  0.005567  0.006531  0.006185  0.005381  0.004033  0.005563  0.007706   \n",
       "\n",
       "    E_AGE17  E_DISABL  E_SNGPNT  E_MINRTY  E_LIMENG   E_MUNIT  E_MOBILE  \\\n",
       "0  0.005894  0.008899  0.004745  0.001800  0.000178  0.000925  0.052169   \n",
       "1  0.018237  0.027808  0.014532  0.004424  0.001841  0.020860  0.144617   \n",
       "2  0.002336  0.004839  0.003149  0.002008  0.000393  0.000142  0.037636   \n",
       "3  0.001927  0.003241  0.001814  0.000783  0.000080  0.000179  0.028200   \n",
       "4  0.005751  0.009986  0.004748  0.000936  0.000683  0.000236  0.065160   \n",
       "\n",
       "    E_CROWD   E_NOVEH  E_GROUPQ  E_UNINSUR  E_DAYPOP    Deaths  diff_E_AGE17  \\\n",
       "0  0.001356  0.001830  0.002516   0.002742  0.004180  0.006714      0.692069   \n",
       "1  0.002554  0.003821  0.014860   0.013371  0.017542  0.029376      0.712167   \n",
       "2  0.000456  0.001352  0.016329   0.001748  0.002802  0.005165      0.693845   \n",
       "3  0.000044  0.000489  0.008970   0.001246  0.001752  0.003034      0.695167   \n",
       "4  0.000880  0.001388  0.003256   0.003279  0.004012  0.008587      0.694401   \n",
       "\n",
       "   diff_E_AGE65  diff_E_CROWD  diff_E_DAYPOP  diff_E_DISABL  diff_E_GROUPQ  \\\n",
       "0      0.007124      0.576842       0.096547       0.110649       0.420372   \n",
       "1      0.051380      0.593545       0.148273       0.137624       0.438211   \n",
       "2      0.004532      0.589660       0.095458       0.096031       0.412185   \n",
       "3      0.003943      0.586200       0.098038       0.105764       0.415633   \n",
       "4      0.007310      0.585034       0.098982       0.091897       0.407963   \n",
       "\n",
       "   diff_E_HH  diff_E_HU  diff_E_LIMENG  diff_E_MINRTY  diff_E_MOBILE  \\\n",
       "0   0.031711   0.024770       0.876535       0.038420       0.271194   \n",
       "1   0.086353   0.086220       0.871263       0.047066       0.247361   \n",
       "2   0.025659   0.018315       0.875425       0.033196       0.331810   \n",
       "3   0.025682   0.018488       0.875806       0.035305       0.342148   \n",
       "4   0.026187   0.020248       0.875246       0.037257       0.340189   \n",
       "\n",
       "   diff_E_MUNIT  diff_E_NOHSDP  diff_E_NOVEH  diff_E_POV  diff_E_SNGPNT  \\\n",
       "0      0.051121       0.939314      0.590011    0.012150       0.996283   \n",
       "1      0.058032       0.946512      0.597397    0.021139       0.984238   \n",
       "2      0.050582       0.942704      0.593741    0.007540       0.996081   \n",
       "3      0.050951       0.941815      0.592382    0.005677       0.997683   \n",
       "4      0.049212       0.931791      0.594161    0.008705       0.994147   \n",
       "\n",
       "   diff_E_TOTPOP  diff_E_UNEMP  diff_E_UNINSUR  \n",
       "0       0.112301      0.973451        0.996829  \n",
       "1       0.163057      0.963419        0.991809  \n",
       "2       0.107344      0.976218        0.996890  \n",
       "3       0.110808      0.978690        0.997368  \n",
       "4       0.111551      0.975524        0.997083  "
      ]
     },
     "execution_count": 26,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "2847"
      ]
     },
     "execution_count": 27,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "len(X)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "2847"
      ]
     },
     "execution_count": 28,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "len(y)"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Multifactor Regression Approach"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Model score on testing data: 0.24038183467255914\n",
      "Model score on training data: 0.8838462378965374\n",
      "\n",
      "Model score on testing data: 0.30436254532434615\n",
      "Model score on training data: 0.8843630894728591\n",
      "\n",
      "Model score on testing data: 0.7060063036861124\n",
      "Model score on training data: 0.8796076961000733\n",
      "\n",
      "Model score on testing data: 0.7427385653310781\n",
      "Model score on training data: 0.8763783224364746\n",
      "\n",
      "Model score on testing data: 0.8901603806185421\n",
      "Model score on training data: 0.8516734602603746\n",
      "\n",
      "Model score on testing data: 0.07146712673637712\n",
      "Model score on training data: 0.8904127836610122\n",
      "\n",
      "Model score on testing data: 0.7939248969610683\n",
      "Model score on training data: 0.8795553382721369\n",
      "\n",
      "Model score on testing data: 0.8912121369665378\n",
      "Model score on training data: 0.8633985682174878\n",
      "\n",
      "Model score on testing data: 0.7327259559550272\n",
      "Model score on training data: 0.8784489229319861\n",
      "\n",
      "Model score on testing data: 0.6985868642218362\n",
      "Model score on training data: 0.8825107875039978\n"
     ]
    }
   ],
   "source": [
    "# Splitting X and y into training datasets\n",
    "kf = KFold(n_splits=10, shuffle=True)\n",
    "# kf = KFold(n_splits=5,random_state=42,shuffle=True)\n",
    "for train_index,val_index in kf.split(X):\n",
    "    X_train,X_test = X.iloc[train_index],X.iloc[val_index],\n",
    "    y_train,y_test = y.iloc[train_index],y.iloc[val_index]\n",
    "\n",
    "    regr = linear_model.LinearRegression()\n",
    "    regr.fit(X_train, y_train)\n",
    "\n",
    "    # testing model for general accuracy\n",
    "    print(f'\\nModel score on testing data: {regr.score(X_test, y_test)}')\n",
    "    print(f'Model score on training data: {regr.score(X_train, y_train)}')\n",
    "\n",
    "    # coef_graph()"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Deep Learning Approach\n",
    "https://machinelearningmastery.com/regression-tutorial-keras-deep-learning-library-python/"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [],
   "source": [
    "# import tensorflow as tf\n",
    "from tensorflow.keras.models import Sequential\n",
    "from tensorflow.keras.layers import Dense\n",
    "from tensorflow_addons.metrics import RSquare\n",
    "from sklearn.model_selection import cross_val_score\n",
    "from scikeras.wrappers import KerasRegressor"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [],
   "source": [
    "# define base model\n",
    "def baseline_model():\n",
    "    # create model\n",
    "    model = Sequential()\n",
    "    model.add(Dense(19, input_shape=(19,), kernel_initializer='normal', activation='relu'))\n",
    "    model.add(Dense(10, kernel_initializer='normal', activation='relu'))\n",
    "    model.add(Dense(1, kernel_initializer='normal'))\n",
    "    # Compile model\n",
    "    # model.compile(loss='mse', optimizer='rmsprop', metrics=[RSquare()])\n",
    "    model.compile(optimizer='rmsprop',loss='mse',metrics=['mse'])\n",
    "\n",
    "    return model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "metadata": {},
   "outputs": [
    {
     "ename": "ValueError",
     "evalue": "\nAll the 10 fits failed.\nIt is very likely that your model is misconfigured.\nYou can try to debug the error by setting error_score='raise'.\n\nBelow are more details about the failures:\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 762, in fit\n    self._fit(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 931, in _fit\n    self._fit_keras_model(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 526, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\alex\\AppData\\Local\\Temp\\__autograph_generated_file7ugr5itw.py\", line 15, in tf__train_function\n    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\nValueError: in user code:\n\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1249, in train_function  *\n        return step_function(self, iterator)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1233, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1222, in run_step  **\n        outputs = model.train_step(data)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1023, in train_step\n        y_pred = self(x, training=True)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\input_spec.py\", line 295, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Input 0 of layer \"sequential\" is incompatible with the layer: expected shape=(None, 19), found shape=(None, 39)\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 762, in fit\n    self._fit(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 931, in _fit\n    self._fit_keras_model(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 526, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\alex\\AppData\\Local\\Temp\\__autograph_generated_file7ugr5itw.py\", line 15, in tf__train_function\n    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\nValueError: in user code:\n\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1249, in train_function  *\n        return step_function(self, iterator)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1233, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1222, in run_step  **\n        outputs = model.train_step(data)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1023, in train_step\n        y_pred = self(x, training=True)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\input_spec.py\", line 295, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Input 0 of layer \"sequential_1\" is incompatible with the layer: expected shape=(None, 19), found shape=(None, 39)\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 762, in fit\n    self._fit(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 931, in _fit\n    self._fit_keras_model(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 526, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\alex\\AppData\\Local\\Temp\\__autograph_generated_file7ugr5itw.py\", line 15, in tf__train_function\n    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\nValueError: in user code:\n\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1249, in train_function  *\n        return step_function(self, iterator)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1233, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1222, in run_step  **\n        outputs = model.train_step(data)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1023, in train_step\n        y_pred = self(x, training=True)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\input_spec.py\", line 295, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Input 0 of layer \"sequential_2\" is incompatible with the layer: expected shape=(None, 19), found shape=(None, 39)\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 762, in fit\n    self._fit(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 931, in _fit\n    self._fit_keras_model(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 526, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\alex\\AppData\\Local\\Temp\\__autograph_generated_file7ugr5itw.py\", line 15, in tf__train_function\n    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\nValueError: in user code:\n\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1249, in train_function  *\n        return step_function(self, iterator)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1233, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1222, in run_step  **\n        outputs = model.train_step(data)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1023, in train_step\n        y_pred = self(x, training=True)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\input_spec.py\", line 295, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Input 0 of layer \"sequential_3\" is incompatible with the layer: expected shape=(None, 19), found shape=(None, 39)\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 762, in fit\n    self._fit(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 931, in _fit\n    self._fit_keras_model(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 526, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\alex\\AppData\\Local\\Temp\\__autograph_generated_file7ugr5itw.py\", line 15, in tf__train_function\n    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\nValueError: in user code:\n\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1249, in train_function  *\n        return step_function(self, iterator)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1233, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1222, in run_step  **\n        outputs = model.train_step(data)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1023, in train_step\n        y_pred = self(x, training=True)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\input_spec.py\", line 295, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Input 0 of layer \"sequential_4\" is incompatible with the layer: expected shape=(None, 19), found shape=(None, 39)\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 762, in fit\n    self._fit(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 931, in _fit\n    self._fit_keras_model(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 526, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\alex\\AppData\\Local\\Temp\\__autograph_generated_file7ugr5itw.py\", line 15, in tf__train_function\n    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\nValueError: in user code:\n\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1249, in train_function  *\n        return step_function(self, iterator)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1233, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1222, in run_step  **\n        outputs = model.train_step(data)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1023, in train_step\n        y_pred = self(x, training=True)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\input_spec.py\", line 295, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Input 0 of layer \"sequential_5\" is incompatible with the layer: expected shape=(None, 19), found shape=(None, 39)\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 762, in fit\n    self._fit(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 931, in _fit\n    self._fit_keras_model(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 526, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\alex\\AppData\\Local\\Temp\\__autograph_generated_file7ugr5itw.py\", line 15, in tf__train_function\n    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\nValueError: in user code:\n\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1249, in train_function  *\n        return step_function(self, iterator)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1233, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1222, in run_step  **\n        outputs = model.train_step(data)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1023, in train_step\n        y_pred = self(x, training=True)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\input_spec.py\", line 295, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Input 0 of layer \"sequential_6\" is incompatible with the layer: expected shape=(None, 19), found shape=(None, 39)\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 762, in fit\n    self._fit(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 931, in _fit\n    self._fit_keras_model(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 526, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\alex\\AppData\\Local\\Temp\\__autograph_generated_file7ugr5itw.py\", line 15, in tf__train_function\n    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\nValueError: in user code:\n\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1249, in train_function  *\n        return step_function(self, iterator)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1233, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1222, in run_step  **\n        outputs = model.train_step(data)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1023, in train_step\n        y_pred = self(x, training=True)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\input_spec.py\", line 295, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Input 0 of layer \"sequential_7\" is incompatible with the layer: expected shape=(None, 19), found shape=(None, 39)\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 762, in fit\n    self._fit(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 931, in _fit\n    self._fit_keras_model(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 526, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\alex\\AppData\\Local\\Temp\\__autograph_generated_file7ugr5itw.py\", line 15, in tf__train_function\n    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\nValueError: in user code:\n\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1249, in train_function  *\n        return step_function(self, iterator)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1233, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1222, in run_step  **\n        outputs = model.train_step(data)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1023, in train_step\n        y_pred = self(x, training=True)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\input_spec.py\", line 295, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Input 0 of layer \"sequential_8\" is incompatible with the layer: expected shape=(None, 19), found shape=(None, 39)\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 762, in fit\n    self._fit(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 931, in _fit\n    self._fit_keras_model(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 526, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\alex\\AppData\\Local\\Temp\\__autograph_generated_file7ugr5itw.py\", line 15, in tf__train_function\n    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\nValueError: in user code:\n\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1249, in train_function  *\n        return step_function(self, iterator)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1233, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1222, in run_step  **\n        outputs = model.train_step(data)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1023, in train_step\n        y_pred = self(x, training=True)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\input_spec.py\", line 295, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Input 0 of layer \"sequential_9\" is incompatible with the layer: expected shape=(None, 19), found shape=(None, 39)\n\n",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[1;32mc:\\Users\\alex\\Documents\\Code\\Investigating-SVI-and-Heart-Related-Deaths\\machine-learning.ipynb Cell 24\u001b[0m in \u001b[0;36m<cell line: 3>\u001b[1;34m()\u001b[0m\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/Users/alex/Documents/Code/Investigating-SVI-and-Heart-Related-Deaths/machine-learning.ipynb#X21sZmlsZQ%3D%3D?line=0'>1</a>\u001b[0m estimator \u001b[39m=\u001b[39m KerasRegressor(model\u001b[39m=\u001b[39mbaseline_model, epochs\u001b[39m=\u001b[39m\u001b[39m50\u001b[39m, batch_size\u001b[39m=\u001b[39m\u001b[39m10\u001b[39m, verbose\u001b[39m=\u001b[39m\u001b[39m0\u001b[39m)\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/Users/alex/Documents/Code/Investigating-SVI-and-Heart-Related-Deaths/machine-learning.ipynb#X21sZmlsZQ%3D%3D?line=1'>2</a>\u001b[0m kfold \u001b[39m=\u001b[39m KFold(n_splits\u001b[39m=\u001b[39m\u001b[39m10\u001b[39m)\n\u001b[1;32m----> <a href='vscode-notebook-cell:/c%3A/Users/alex/Documents/Code/Investigating-SVI-and-Heart-Related-Deaths/machine-learning.ipynb#X21sZmlsZQ%3D%3D?line=2'>3</a>\u001b[0m results \u001b[39m=\u001b[39m cross_val_score(estimator, X_train, y_train, cv\u001b[39m=\u001b[39;49mkfold, scoring\u001b[39m=\u001b[39;49m\u001b[39m'\u001b[39;49m\u001b[39mneg_mean_absolute_error\u001b[39;49m\u001b[39m'\u001b[39;49m)\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/Users/alex/Documents/Code/Investigating-SVI-and-Heart-Related-Deaths/machine-learning.ipynb#X21sZmlsZQ%3D%3D?line=3'>4</a>\u001b[0m \u001b[39mprint\u001b[39m(\u001b[39m\"\u001b[39m\u001b[39mResults: \u001b[39m\u001b[39m%.2f\u001b[39;00m\u001b[39m (\u001b[39m\u001b[39m%.2f\u001b[39;00m\u001b[39m) MSE\u001b[39m\u001b[39m\"\u001b[39m \u001b[39m%\u001b[39m (results\u001b[39m.\u001b[39mmean(), results\u001b[39m.\u001b[39mstd()))\n",
      "File \u001b[1;32m~\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\sklearn\\model_selection\\_validation.py:515\u001b[0m, in \u001b[0;36mcross_val_score\u001b[1;34m(estimator, X, y, groups, scoring, cv, n_jobs, verbose, fit_params, pre_dispatch, error_score)\u001b[0m\n\u001b[0;32m    512\u001b[0m \u001b[39m# To ensure multimetric format is not supported\u001b[39;00m\n\u001b[0;32m    513\u001b[0m scorer \u001b[39m=\u001b[39m check_scoring(estimator, scoring\u001b[39m=\u001b[39mscoring)\n\u001b[1;32m--> 515\u001b[0m cv_results \u001b[39m=\u001b[39m cross_validate(\n\u001b[0;32m    516\u001b[0m     estimator\u001b[39m=\u001b[39;49mestimator,\n\u001b[0;32m    517\u001b[0m     X\u001b[39m=\u001b[39;49mX,\n\u001b[0;32m    518\u001b[0m     y\u001b[39m=\u001b[39;49my,\n\u001b[0;32m    519\u001b[0m     groups\u001b[39m=\u001b[39;49mgroups,\n\u001b[0;32m    520\u001b[0m     scoring\u001b[39m=\u001b[39;49m{\u001b[39m\"\u001b[39;49m\u001b[39mscore\u001b[39;49m\u001b[39m\"\u001b[39;49m: scorer},\n\u001b[0;32m    521\u001b[0m     cv\u001b[39m=\u001b[39;49mcv,\n\u001b[0;32m    522\u001b[0m     n_jobs\u001b[39m=\u001b[39;49mn_jobs,\n\u001b[0;32m    523\u001b[0m     verbose\u001b[39m=\u001b[39;49mverbose,\n\u001b[0;32m    524\u001b[0m     fit_params\u001b[39m=\u001b[39;49mfit_params,\n\u001b[0;32m    525\u001b[0m     pre_dispatch\u001b[39m=\u001b[39;49mpre_dispatch,\n\u001b[0;32m    526\u001b[0m     error_score\u001b[39m=\u001b[39;49merror_score,\n\u001b[0;32m    527\u001b[0m )\n\u001b[0;32m    528\u001b[0m \u001b[39mreturn\u001b[39;00m cv_results[\u001b[39m\"\u001b[39m\u001b[39mtest_score\u001b[39m\u001b[39m\"\u001b[39m]\n",
      "File \u001b[1;32m~\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\sklearn\\model_selection\\_validation.py:285\u001b[0m, in \u001b[0;36mcross_validate\u001b[1;34m(estimator, X, y, groups, scoring, cv, n_jobs, verbose, fit_params, pre_dispatch, return_train_score, return_estimator, error_score)\u001b[0m\n\u001b[0;32m    265\u001b[0m parallel \u001b[39m=\u001b[39m Parallel(n_jobs\u001b[39m=\u001b[39mn_jobs, verbose\u001b[39m=\u001b[39mverbose, pre_dispatch\u001b[39m=\u001b[39mpre_dispatch)\n\u001b[0;32m    266\u001b[0m results \u001b[39m=\u001b[39m parallel(\n\u001b[0;32m    267\u001b[0m     delayed(_fit_and_score)(\n\u001b[0;32m    268\u001b[0m         clone(estimator),\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    282\u001b[0m     \u001b[39mfor\u001b[39;00m train, test \u001b[39min\u001b[39;00m cv\u001b[39m.\u001b[39msplit(X, y, groups)\n\u001b[0;32m    283\u001b[0m )\n\u001b[1;32m--> 285\u001b[0m _warn_or_raise_about_fit_failures(results, error_score)\n\u001b[0;32m    287\u001b[0m \u001b[39m# For callabe scoring, the return type is only know after calling. If the\u001b[39;00m\n\u001b[0;32m    288\u001b[0m \u001b[39m# return type is a dictionary, the error scores can now be inserted with\u001b[39;00m\n\u001b[0;32m    289\u001b[0m \u001b[39m# the correct key.\u001b[39;00m\n\u001b[0;32m    290\u001b[0m \u001b[39mif\u001b[39;00m callable(scoring):\n",
      "File \u001b[1;32m~\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\sklearn\\model_selection\\_validation.py:367\u001b[0m, in \u001b[0;36m_warn_or_raise_about_fit_failures\u001b[1;34m(results, error_score)\u001b[0m\n\u001b[0;32m    360\u001b[0m \u001b[39mif\u001b[39;00m num_failed_fits \u001b[39m==\u001b[39m num_fits:\n\u001b[0;32m    361\u001b[0m     all_fits_failed_message \u001b[39m=\u001b[39m (\n\u001b[0;32m    362\u001b[0m         \u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39mAll the \u001b[39m\u001b[39m{\u001b[39;00mnum_fits\u001b[39m}\u001b[39;00m\u001b[39m fits failed.\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[0;32m    363\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mIt is very likely that your model is misconfigured.\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[0;32m    364\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mYou can try to debug the error by setting error_score=\u001b[39m\u001b[39m'\u001b[39m\u001b[39mraise\u001b[39m\u001b[39m'\u001b[39m\u001b[39m.\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m\\n\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[0;32m    365\u001b[0m         \u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mBelow are more details about the failures:\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m{\u001b[39;00mfit_errors_summary\u001b[39m}\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[0;32m    366\u001b[0m     )\n\u001b[1;32m--> 367\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mValueError\u001b[39;00m(all_fits_failed_message)\n\u001b[0;32m    369\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m    370\u001b[0m     some_fits_failed_message \u001b[39m=\u001b[39m (\n\u001b[0;32m    371\u001b[0m         \u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m{\u001b[39;00mnum_failed_fits\u001b[39m}\u001b[39;00m\u001b[39m fits failed out of a total of \u001b[39m\u001b[39m{\u001b[39;00mnum_fits\u001b[39m}\u001b[39;00m\u001b[39m.\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[0;32m    372\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mThe score on these train-test partitions for these parameters\u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    376\u001b[0m         \u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mBelow are more details about the failures:\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m{\u001b[39;00mfit_errors_summary\u001b[39m}\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[0;32m    377\u001b[0m     )\n",
      "\u001b[1;31mValueError\u001b[0m: \nAll the 10 fits failed.\nIt is very likely that your model is misconfigured.\nYou can try to debug the error by setting error_score='raise'.\n\nBelow are more details about the failures:\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 762, in fit\n    self._fit(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 931, in _fit\n    self._fit_keras_model(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 526, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\alex\\AppData\\Local\\Temp\\__autograph_generated_file7ugr5itw.py\", line 15, in tf__train_function\n    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\nValueError: in user code:\n\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1249, in train_function  *\n        return step_function(self, iterator)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1233, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1222, in run_step  **\n        outputs = model.train_step(data)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1023, in train_step\n        y_pred = self(x, training=True)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\input_spec.py\", line 295, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Input 0 of layer \"sequential\" is incompatible with the layer: expected shape=(None, 19), found shape=(None, 39)\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 762, in fit\n    self._fit(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 931, in _fit\n    self._fit_keras_model(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 526, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\alex\\AppData\\Local\\Temp\\__autograph_generated_file7ugr5itw.py\", line 15, in tf__train_function\n    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\nValueError: in user code:\n\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1249, in train_function  *\n        return step_function(self, iterator)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1233, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1222, in run_step  **\n        outputs = model.train_step(data)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1023, in train_step\n        y_pred = self(x, training=True)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\input_spec.py\", line 295, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Input 0 of layer \"sequential_1\" is incompatible with the layer: expected shape=(None, 19), found shape=(None, 39)\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 762, in fit\n    self._fit(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 931, in _fit\n    self._fit_keras_model(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 526, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\alex\\AppData\\Local\\Temp\\__autograph_generated_file7ugr5itw.py\", line 15, in tf__train_function\n    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\nValueError: in user code:\n\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1249, in train_function  *\n        return step_function(self, iterator)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1233, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1222, in run_step  **\n        outputs = model.train_step(data)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1023, in train_step\n        y_pred = self(x, training=True)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\input_spec.py\", line 295, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Input 0 of layer \"sequential_2\" is incompatible with the layer: expected shape=(None, 19), found shape=(None, 39)\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 762, in fit\n    self._fit(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 931, in _fit\n    self._fit_keras_model(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 526, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\alex\\AppData\\Local\\Temp\\__autograph_generated_file7ugr5itw.py\", line 15, in tf__train_function\n    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\nValueError: in user code:\n\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1249, in train_function  *\n        return step_function(self, iterator)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1233, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1222, in run_step  **\n        outputs = model.train_step(data)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1023, in train_step\n        y_pred = self(x, training=True)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\input_spec.py\", line 295, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Input 0 of layer \"sequential_3\" is incompatible with the layer: expected shape=(None, 19), found shape=(None, 39)\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 762, in fit\n    self._fit(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 931, in _fit\n    self._fit_keras_model(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 526, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\alex\\AppData\\Local\\Temp\\__autograph_generated_file7ugr5itw.py\", line 15, in tf__train_function\n    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\nValueError: in user code:\n\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1249, in train_function  *\n        return step_function(self, iterator)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1233, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1222, in run_step  **\n        outputs = model.train_step(data)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1023, in train_step\n        y_pred = self(x, training=True)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\input_spec.py\", line 295, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Input 0 of layer \"sequential_4\" is incompatible with the layer: expected shape=(None, 19), found shape=(None, 39)\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 762, in fit\n    self._fit(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 931, in _fit\n    self._fit_keras_model(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 526, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\alex\\AppData\\Local\\Temp\\__autograph_generated_file7ugr5itw.py\", line 15, in tf__train_function\n    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\nValueError: in user code:\n\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1249, in train_function  *\n        return step_function(self, iterator)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1233, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1222, in run_step  **\n        outputs = model.train_step(data)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1023, in train_step\n        y_pred = self(x, training=True)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\input_spec.py\", line 295, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Input 0 of layer \"sequential_5\" is incompatible with the layer: expected shape=(None, 19), found shape=(None, 39)\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 762, in fit\n    self._fit(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 931, in _fit\n    self._fit_keras_model(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 526, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\alex\\AppData\\Local\\Temp\\__autograph_generated_file7ugr5itw.py\", line 15, in tf__train_function\n    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\nValueError: in user code:\n\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1249, in train_function  *\n        return step_function(self, iterator)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1233, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1222, in run_step  **\n        outputs = model.train_step(data)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1023, in train_step\n        y_pred = self(x, training=True)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\input_spec.py\", line 295, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Input 0 of layer \"sequential_6\" is incompatible with the layer: expected shape=(None, 19), found shape=(None, 39)\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 762, in fit\n    self._fit(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 931, in _fit\n    self._fit_keras_model(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 526, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\alex\\AppData\\Local\\Temp\\__autograph_generated_file7ugr5itw.py\", line 15, in tf__train_function\n    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\nValueError: in user code:\n\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1249, in train_function  *\n        return step_function(self, iterator)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1233, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1222, in run_step  **\n        outputs = model.train_step(data)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1023, in train_step\n        y_pred = self(x, training=True)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\input_spec.py\", line 295, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Input 0 of layer \"sequential_7\" is incompatible with the layer: expected shape=(None, 19), found shape=(None, 39)\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 762, in fit\n    self._fit(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 931, in _fit\n    self._fit_keras_model(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 526, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\alex\\AppData\\Local\\Temp\\__autograph_generated_file7ugr5itw.py\", line 15, in tf__train_function\n    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\nValueError: in user code:\n\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1249, in train_function  *\n        return step_function(self, iterator)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1233, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1222, in run_step  **\n        outputs = model.train_step(data)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1023, in train_step\n        y_pred = self(x, training=True)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\input_spec.py\", line 295, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Input 0 of layer \"sequential_8\" is incompatible with the layer: expected shape=(None, 19), found shape=(None, 39)\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 762, in fit\n    self._fit(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 931, in _fit\n    self._fit_keras_model(\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\scikeras\\wrappers.py\", line 526, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\alex\\AppData\\Local\\Temp\\__autograph_generated_file7ugr5itw.py\", line 15, in tf__train_function\n    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\nValueError: in user code:\n\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1249, in train_function  *\n        return step_function(self, iterator)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1233, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1222, in run_step  **\n        outputs = model.train_step(data)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\training.py\", line 1023, in train_step\n        y_pred = self(x, training=True)\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"C:\\Users\\alex\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\keras\\engine\\input_spec.py\", line 295, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Input 0 of layer \"sequential_9\" is incompatible with the layer: expected shape=(None, 19), found shape=(None, 39)\n\n"
     ]
    }
   ],
   "source": [
    "estimator = KerasRegressor(model=baseline_model, epochs=50, batch_size=10, verbose=0)\n",
    "kfold = KFold(n_splits=10)\n",
    "results = cross_val_score(estimator, X_train, y_train, cv=kfold, scoring='neg_mean_absolute_error')\n",
    "print(\"Results: %.2f (%.2f) MSE\" % (results.mean(), results.std()))"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Notes\n",
    "\n",
    "__r2 metric__\n",
    "- (19, 38, 1) - model.compile(loss='mse', optimizer='rmsprop', metrics=[RSquare()]) - epochs=200, batch_size=10, verbose=0 - 51%\n",
    "- (19, 10, 1) - model.compile(loss='mse', optimizer='rmsprop', metrics=[RSquare()]) - epochs=200, batch_size=10, verbose=0 - 39%"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Implmenting Automatic Hyperparameter Tuning\n",
    "https://towardsdatascience.com/hyperparameter-tuning-with-keras-tuner-283474fbfbe"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from keras_tuner import HyperModel\n",
    "from tensorflow.keras import models, layers\n",
    "\n",
    "class RegressionHyperModel(HyperModel):\n",
    "    def __init__(self, input_shape):\n",
    "        self.input_shape = input_shape \n",
    "   \n",
    "    def build(self, hp):\n",
    "        model = Sequential()\n",
    "        model.add(\n",
    "            layers.Dense(\n",
    "                units=hp.Int('units', 8, 64, 4, default=8),\n",
    "                activation=hp.Choice(\n",
    "                    'dense_activation',\n",
    "                    values=['relu', 'tanh', 'sigmoid'],\n",
    "                    default='relu'),\n",
    "                input_shape=input_shape\n",
    "            )\n",
    "        )\n",
    "        \n",
    "        model.add(\n",
    "            layers.Dense(\n",
    "                units=hp.Int('units', 16, 64, 4, default=16),\n",
    "                activation=hp.Choice(\n",
    "                    'dense_activation',\n",
    "                    values=['relu', 'tanh', 'sigmoid'],\n",
    "                    default='relu')\n",
    "            )\n",
    "        )\n",
    "        \n",
    "        model.add(\n",
    "            layers.Dropout(\n",
    "                hp.Float(\n",
    "                    'dropout',\n",
    "                    min_value=0.0,\n",
    "                    max_value=0.1,\n",
    "                    default=0.005,\n",
    "                    step=0.01)\n",
    "            )\n",
    "        )\n",
    "        \n",
    "        model.add(layers.Dense(1))\n",
    "        \n",
    "        model.compile(\n",
    "            optimizer='rmsprop',loss='mse',metrics=['mse']\n",
    "            # loss='mse', optimizer='rmsprop', metrics=[RSquare()]\n",
    "        )\n",
    "        \n",
    "        return model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "input_shape = (X_train.shape[1],)\n",
    "hypermodel = RegressionHyperModel(input_shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from keras_tuner import RandomSearch\n",
    "tuner_rs = RandomSearch(\n",
    "            hypermodel,\n",
    "            objective='mse',\n",
    "            seed=42,\n",
    "            max_trials=10,\n",
    "            executions_per_trial=2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "tuner_rs.search(X_train, y_train, epochs=50, validation_split=0.2, verbose=0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "best_model = tuner_rs.get_best_models(num_models=1)[0]\n",
    "loss, mse = best_model.evaluate(X_test, y_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "796a2b5adaaa842c9b78e62f6009df4de6b28861ed15d27911e5c87767f65f4d"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
